apiVersion: 1

datasources:
  - name: ClickHouse
    type: grafana-clickhouse-datasource
    access: proxy
    url: http://classify-clickhouse:8123
    jsonData:
      defaultDatabase: otel
      port: 9000
      server: classify-clickhouse
      username: default
      tlsSkipVerify: true
    secureJsonData:
      password: "otel123"
    isDefault: true
    editable: true
